apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route-trigger-api
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - kind: Rule
    match: PathPrefix(`/api/v1`)
    services:
    - kind: Service
      name: trigger-api
      port: 8080
