apiVersion: v1
kind: Secret
metadata:
  name: authsecret
data:
  # test:test
  # test2:test2
  users: |2
    dGVzdDokYXByMSRINnVza2trVyRJZ1hMUDZld1RyU3VCa1RycUU4d2ovCnRlc3QyOiRhcHIxJGQ5
    aHI5SEJCJDRIeHdnVWlyM0hQNEVzZ2dQL1FObzAK
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-auth
spec:
  basicAuth:
    secret: authsecret
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route-traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - kind: Rule
    match: PathPrefix(`/api`)
    middlewares:
    - name: traefik-auth
    services:
    - kind: Service
      name: platform-api
      port: 8080
  - kind: Rule
    match: PathPrefix(`/`)
    middlewares:
    - name: traefik-auth
    services:
    - kind: Service
      name: platform-frontend
      port: 3000
